backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "src/images/portfolio" 
public_folder: "/images/portfolio"

collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "/src/portfolio/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "portfolio"}
      - {label: "Featured?", hint: "will put this article on your home page", name: "featured", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string", required}
      - {label: "Journal", hint: "where this was published (e.g. 'the Mail on Sunday')", name: "journal", widget: "string", required}
      - {label: "Publish Date", name: "date", widget: "datetime", required}
      - {label: "Headline image", hint: "ideally under 300kb", name: "image", widget: "image", required}
      - {label: "Thumb", hint: "ideally under 80kb", name: "thumb", widget: "image", required}
      - {label: "Article content", name: "body", widget: "markdown", required}
      - {label: "Downloadable PDF", name: "pdf", widget: "file"}