backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: https://wardles.netlify.app
media-folder: "src/portfolio/"
media-folder: "/portfolio/"

collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Article" # Used in the UI
    folder: "src/portfolio/" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: ''
    public_folder: ''
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "slug", name: "slug", widget: "hidden", default: "{{slug}}"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "portfolio"}
      - {label: "Featured?", hint: "will put this article on your home page", name: "featured", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Journal", hint: "where this was published (e.g. 'the Mail on Sunday')", name: "journal", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Headline image", hint: "ideally under 300kb", name: "image", widget: "image"}
      - {label: "Thumb", hint: "ideally under 80kb", name: "thumb", widget: "image"}
      - {label: "Article content", name: "body", widget: "markdown"}
      - {label: "Downloadable PDF", name: "pdf", widget: "file", required: false}