backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

display_url: "wardles.netlify.app"
media_folder: "src/media/"
public_folder: "/media"
collections:
  - name: "portfolio"
    label: "Articles"
    label_singular: "Article"
    folder: "src/portfolio/articles"
    path: "{{slug}}-{{second}}{{minute}}/index"
    create: true
    media_folder: ""
    public_folder: ""
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "portfolio.njk"}
      - {label: "tags", name: "tags", widget: "hidden", default: "portfolio"}
      - {label: "Featured?", hint: "will put this article on your home page", name: "featured", widget: "boolean", default: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Journal", hint: "where this was published (e.g. 'the Mail on Sunday')", name: "journal", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Headline image", hint: "ideally under 300kb", name: "image", widget: "image"}
      - {label: "Thumb", hint: "ideally under 80kb", name: "thumb", widget: "image"}
      - {label: "Article content", name: "body", widget: "markdown"}
      - {label: "Downloadable PDF", name: "pdf", widget: "file", required: false}